[build-system]
requires = ['setuptools < 58.0.0', 'wheel']

[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.domino
  | build
  | dist
  | __pycache__
)/
'''
