[build-system]
requires = ['setuptools >= 42.0.0, < 58', 'wheel']
build-backend = 'setuptools.build_meta'

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.domino
  | build
  | dist
  | __pycache__
)/
'''
